These are photos taken at the first real-life SuperTux Developers' Meeting.
[[Image:Meeting_01.jpg|center|frame|Stephen (graphics), Matze (code) and Marek (music, levels)]]
[[Image:Meeting_09.jpg|center|frame|The official meeting logo :-)]]
[[Image:Meeting_10.jpg|center|frame|Meeting logo II]]
[[Image:Meeting_02.jpg|center|frame|Matze and Stephen]]
[[Image:Meeting_03.jpg|center|frame|Milestone 2 work in progress]]
[[Image:Meeting_05.jpg|center|frame|Sightseeing Tour - Marek and Stephen in front of Nolok's Castle :-)]]
[[Image:Meeting_07.jpg|center|frame|Monday morning coding]]
[[Image:Meeting_11.jpg|center|frame|Matze at work]]
[[Image:Meeting_13.jpg|center|frame|Marek with the SuperTux soundtrack]]
[[Image:Meeting_12.jpg|center|frame|"You guys are not as scary as I thought you were." -- Stephen G.]]
[[Image:Meeting_14.jpg|center|frame|Marek building levels]]
[[Image:Pizza.jpg|center|frame|Special thanks to Nina for supplying the wonderful homemade pizzas!]]
