ce serais bien qu'on puisse créer les niveaux (level editor) dans tous les supertux...
:Translation "it'd be that one can create levels (level editor) in all supertux ..."
:This isn't the place for this kind of conversation, [[SuperTux:Community_Discussion|this]] is one place where that type of discussion is allowed, and there is already a [[Editor_FAQ|level editor]]. -- Qwood [[Special:Contributions/Qwood|(contribs)]] [[User talk:Qwood|(talk)]] 03:04, 7 June 2011 (UTC)
