== Last minute announcement. ==

If you don't want new people to participate just say so. No need to announce the meeting just hours before it starts in pretending to be open. I bet the inner circle knew the date weeks in advance. I can't cancel my evening plans now. But you don't want new contributors anyway.

: We knew we wanted a meeting for a while ("next meeting" plans have been floating around the [[Milestone 2 Design Document#Next Meeting Agenda (7. August 2008, 18:00 GMT)|wiki]] for ages). Octo suggested a meeting on supertux-devel at FOSDEM on the 28th. sik0fewl replied that that wouldn't work. Octo asked as to when a good meeting time would be.
: WolfgangB asked on the [http://lists.lethargik.org/listinfo.cgi/supertux-team-lethargik.org supertux-team] mailing list which time zones developers were living in. Octo asked why it was on supertux-team instead of supertux-devel. sik0fewl replied that there would be too much chatter. Sommer created a [http://www.doodle.com/asgkxvv2uvbyyuq7 poll] which showed that Sunday was a good time and suggested posting it back to supertux-devel.
: The rest of the discussion continued on supertux-devel. I suggested sometime in 18:00 - 24:00 UTC. It was finalized Saturday on IRC at around 15:00 UTC (8 am my time) after grumbel said he could come. I went AFK for a while and returned at 1:00 UTC (6 pm my time). I then sent out a message announcing the meeting 22 minutes later. Most people didn't have anything else to do and came.
: I hope this clears up how the meeting was planned. It really was at nearly the last minute. The "inner circle" discussed nothing but the poll and whether we wanted an open meeting. Everyone else knew as little as you did. Please accept my sincere apologies for announcing it late. Maybe you can come to the meeting next week? --[[User:Mathnerd314|Mathnerd314]] 22:45, 14 February 2010 (UTC)
: Hi, sorry about the late announcement. We don't want to exclude anyone, we're merely lacking organization. The next meeting is announced for ''Saturday, February&nbsp;20<sup>th</sup>'', hope you can make that. Regards, --[[User:Octo|octo]] 15:35, 15 February 2010 (UTC)
