*Julius Freezer, stop suggesting so many world types.
*Grumbel, I think you'd be the best judge of the ship/Water World idea.
*Wantsi, I bet you could compose some interesting music for aboard a ship...
